name: Exported files

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Check exported files"
        run: |
          EXPECTED="LICENSE,README.md,RELEASES.md,SECURITY.md,composer.json,package.json"
          CURRENT="$(git archive HEAD | tar --list --exclude="asset" --exclude="asset/*" --exclude="src" --exclude="src/*" | paste -s -d ",")"
          echo "CURRENT =${CURRENT}"
          echo "EXPECTED=${EXPECTED}"
          test "${CURRENT}" == "${EXPECTED}"
